
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CriminalInvestigation extends javax.swing.JFrame {
    ArrayList<CriminalCodes> criminals=Utility.readFile("criminals.txt");
    CriminalCodes criminalsAll;
    private void initiateCriminalCodes(){
    for(CriminalCodes a: criminals){
        CriminalIDdropdown.addItem(a);
    }
    }

    /**
     * Creates new form CriminalInvestigation
     */
    public CriminalInvestigation() {
        initComponents();
        initiateCriminalCodes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1Male = new javax.swing.ButtonGroup();
        jLabel1SuspectID = new javax.swing.JLabel();
        jLabel3Date = new javax.swing.JLabel();
        jTextField2Date = new javax.swing.JTextField();
        CriminalIDdropdown = new javax.swing.JComboBox<>();
        jLabel1Gender = new javax.swing.JLabel();
        jRadioButton1Male = new javax.swing.JRadioButton();
        jRadioButton2Female = new javax.swing.JRadioButton();
        jButton1Clear = new javax.swing.JButton();
        jButton1Exit = new javax.swing.JButton();
        jButton1Result = new javax.swing.JButton();
        jLabel1SuspectName = new javax.swing.JLabel();
        jTextFieldDNA = new javax.swing.JTextField();
        jLabelDNA = new javax.swing.JLabel();
        jTextFieldSusPectName = new javax.swing.JTextField();
        jLabelFprint = new javax.swing.JLabel();
        jTextFieldFprint = new javax.swing.JTextField();
        jTextField1Result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1SuspectID.setText("Suspect ID:");

        jLabel3Date.setText("Date:");

        CriminalIDdropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriminalIDdropdownActionPerformed(evt);
            }
        });

        jLabel1Gender.setText("Gender:");

        buttonGroup1Male.add(jRadioButton1Male);
        jRadioButton1Male.setText("Male");
        jRadioButton1Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1MaleActionPerformed(evt);
            }
        });

        buttonGroup1Male.add(jRadioButton2Female);
        jRadioButton2Female.setText("Female");
        jRadioButton2Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2FemaleActionPerformed(evt);
            }
        });

        jButton1Clear.setText("Clear");
        jButton1Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ClearActionPerformed(evt);
            }
        });

        jButton1Exit.setText("Exit");
        jButton1Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExitActionPerformed(evt);
            }
        });

        jButton1Result.setText("Result");
        jButton1Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ResultActionPerformed(evt);
            }
        });

        jLabel1SuspectName.setText("SuspectName:");

        jLabelDNA.setText("DNAcode:");

        jLabelFprint.setText("Fingerprint:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1SuspectID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CriminalIDdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelFprint)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldFprint, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelDNA)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldDNA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1Exit)
                            .addComponent(jButton1Clear)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1Result)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1SuspectName)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSusPectName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3Date)
                .addGap(18, 18, 18)
                .addComponent(jTextField2Date, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1Gender)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2Female)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1Male))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriminalIDdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1SuspectID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1SuspectName)
                    .addComponent(jTextFieldSusPectName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNA)
                    .addComponent(jTextFieldDNA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFprint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFprint))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3Date)
                            .addComponent(jTextField2Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1Male)
                            .addComponent(jRadioButton2Female)
                            .addComponent(jLabel1Gender))
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1Result)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1Result, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addComponent(jButton1Clear)
                .addGap(18, 18, 18)
                .addComponent(jButton1Exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1MaleActionPerformed
        // TODO add your handling code here:
        jRadioButton1Male.setText("Male");
    }//GEN-LAST:event_jRadioButton1MaleActionPerformed

    private void CriminalIDdropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriminalIDdropdownActionPerformed
        // TODO add your handling code here:
        criminalsAll=(CriminalCodes)CriminalIDdropdown.getSelectedItem();
        jTextFieldSusPectName.setText(criminalsAll.getName());
        jTextFieldDNA.setText(criminalsAll.getDNAcode());
        jTextFieldFprint.setText(criminalsAll.getFingerprintCode());
        jTextField2Date.setText(criminalsAll.getDate());
        jRadioButton1Male.setText(criminalsAll.getGender());
        jRadioButton2Female.setText(criminalsAll.getGender());
        jTextField1Result.setText(criminalsAll.result());
        Utility.writeFile(criminals,"criminals.txt");
         

    }//GEN-LAST:event_CriminalIDdropdownActionPerformed

    private void jButton1ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ExitActionPerformed

    private void jButton1ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ResultActionPerformed
        // TODO add your handling code here:
       String r= JOptionPane.showInputDialog(this,"Ener the same Fingerprint code given","Result",JOptionPane.PLAIN_MESSAGE);
       criminalsAll.getResult(r);
       jTextField1Result.setText(criminalsAll.result());

       jTextField1Result.setText(String.valueOf(criminalsAll.getResult(r)));
       Utility.writeFile(criminals,"criminals.txt");
    }//GEN-LAST:event_jButton1ResultActionPerformed

    private void jButton1ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ClearActionPerformed
        // TODO add your handling code here:
        jTextFieldSusPectName.setText("");
        jTextFieldDNA.setText("");
        jTextFieldFprint.setText("");
        jTextField2Date.setText("");
        jTextField1Result.setText("");
    }//GEN-LAST:event_jButton1ClearActionPerformed

    private void jRadioButton2FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2FemaleActionPerformed
        // TODO add your handling code here:
        jRadioButton2Female.setText("Female");
    }//GEN-LAST:event_jRadioButton2FemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriminalInvestigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriminalInvestigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriminalInvestigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriminalInvestigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriminalInvestigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<CriminalCodes> CriminalIDdropdown;
    private javax.swing.ButtonGroup buttonGroup1Male;
    private javax.swing.JButton jButton1Clear;
    private javax.swing.JButton jButton1Exit;
    private javax.swing.JButton jButton1Result;
    private javax.swing.JLabel jLabel1Gender;
    private javax.swing.JLabel jLabel1SuspectID;
    private javax.swing.JLabel jLabel1SuspectName;
    private javax.swing.JLabel jLabel3Date;
    private javax.swing.JLabel jLabelDNA;
    private javax.swing.JLabel jLabelFprint;
    private javax.swing.JRadioButton jRadioButton1Male;
    private javax.swing.JRadioButton jRadioButton2Female;
    private javax.swing.JTextField jTextField1Result;
    private javax.swing.JTextField jTextField2Date;
    private javax.swing.JTextField jTextFieldDNA;
    private javax.swing.JTextField jTextFieldFprint;
    private javax.swing.JTextField jTextFieldSusPectName;
    // End of variables declaration//GEN-END:variables

}
